"""
Generate a comprehensive demo model for CinemaLens.
Creates all required model artifacts in the static/ directory with 500+ movies.
"""
import json
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix, save_npz
from pathlib import Path
import random

OUTPUT_DIR = Path("static")
OUTPUT_DIR.mkdir(exist_ok=True)

# --- Comprehensive movie database (500+ popular movies) ---
movies_data = [
    # Classic Drama
    {"id": 278, "title": "The Shawshank Redemption", "release_date": "1994-09-23", "primary_company": "Castle Rock Entertainment", "genres": ["drama"], "vote_average": 8.7, "vote_count": 24000, "popularity": 80.0, "overview": "Two imprisoned men bond over a number of years finding solace and eventual redemption through acts of common decency", "imdb_id": "tt0111161", "poster_path": None},
    {"id": 238, "title": "The Godfather", "release_date": "1972-03-14", "primary_company": "Paramount Pictures", "genres": ["drama", "crime"], "vote_average": 8.7, "vote_count": 18000, "popularity": 75.0, "overview": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son", "imdb_id": "tt0068646", "poster_path": None},
    {"id": 240, "title": "The Godfather Part II", "release_date": "1974-12-20", "primary_company": "Paramount Pictures", "genres": ["drama", "crime"], "vote_average": 8.6, "vote_count": 11000, "popularity": 60.0, "overview": "The early life and career of Vito Corleone in 1920s New York City is portrayed while his son Michael expands and tightens his grip on the family crime syndicate", "imdb_id": "tt0071562", "poster_path": None},
    {"id": 424, "title": "Schindler's List", "release_date": "1993-12-15", "primary_company": "Universal Pictures", "genres": ["drama", "history", "war"], "vote_average": 8.6, "vote_count": 14000, "popularity": 60.0, "overview": "In German occupied Poland industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis", "imdb_id": "tt0108052", "poster_path": None},
    {"id": 550, "title": "Fight Club", "release_date": "1999-10-15", "primary_company": "20th Century Fox", "genres": ["drama", "thriller"], "vote_average": 8.4, "vote_count": 26000, "popularity": 73.0, "overview": "An insomniac office worker and a devil may care soap maker form an underground fight club that evolves into something much more", "imdb_id": "tt0137523", "poster_path": None},
    {"id": 13, "title": "Forrest Gump", "release_date": "1994-07-06", "primary_company": "Paramount Pictures", "genres": ["drama", "romance", "comedy"], "vote_average": 8.5, "vote_count": 24000, "popularity": 72.0, "overview": "The presidencies of Kennedy and Johnson and events of Vietnam unfold through the perspective of an Alabama man with an IQ of 75", "imdb_id": "tt0109830", "poster_path": None},
    {"id": 769, "title": "GoodFellas", "release_date": "1990-09-19", "primary_company": "Warner Bros.", "genres": ["drama", "crime"], "vote_average": 8.5, "vote_count": 11000, "popularity": 55.0, "overview": "The story of Henry Hill and his life in the mob covering his relationship with his wife Karen Hill and his mob partners", "imdb_id": "tt0099685", "poster_path": None},
    {"id": 667, "title": "12 Angry Men", "release_date": "1957-04-10", "primary_company": "Orion Nova Productions", "genres": ["drama"], "vote_average": 8.5, "vote_count": 7000, "popularity": 35.0, "overview": "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence", "imdb_id": "tt0050083", "poster_path": None},
    {"id": 346, "title": "Seven Samurai", "release_date": "1954-04-26", "primary_company": "Toho", "genres": ["drama", "action"], "vote_average": 8.5, "vote_count": 3200, "popularity": 30.0, "overview": "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves", "imdb_id": "tt0047478", "poster_path": None},
    {"id": 510, "title": "One Flew Over the Cuckoo's Nest", "release_date": "1975-11-19", "primary_company": "United Artists", "genres": ["drama"], "vote_average": 8.4, "vote_count": 9200, "popularity": 45.0, "overview": "A criminal pleads insanity and is admitted to a mental institution where he rebels against the oppressive nurse and rallies up the scared patients", "imdb_id": "tt0073486", "poster_path": None},
    {"id": 637, "title": "Life Is Beautiful", "release_date": "1997-12-20", "primary_company": "Melampo Cinematografica", "genres": ["drama", "comedy", "romance"], "vote_average": 8.5, "vote_count": 11500, "popularity": 48.0, "overview": "When an open minded Jewish librarian and his son become victims of the Holocaust he uses a perfect mixture of will guile and humor to protect his son", "imdb_id": "tt0118799", "poster_path": None},
    {"id": 372058, "title": "Your Name", "release_date": "2016-08-26", "primary_company": "CoMix Wave Films", "genres": ["animation", "romance", "drama"], "vote_average": 8.5, "vote_count": 10000, "popularity": 55.0, "overview": "Two strangers find themselves linked in a bizarre way when a connection forms will distance be the only thing to keep them apart", "imdb_id": "tt5311514", "poster_path": None},
    {"id": 497, "title": "The Green Mile", "release_date": "1999-12-10", "primary_company": "Castle Rock Entertainment", "genres": ["drama", "fantasy", "crime"], "vote_average": 8.5, "vote_count": 15000, "popularity": 55.0, "overview": "The lives of guards on Death Row are affected by one of their charges a black man accused of child murder and who has a mysterious gift", "imdb_id": "tt0120689", "poster_path": None},
    {"id": 389, "title": "12 Years a Slave", "release_date": "2013-10-18", "primary_company": "Plan B Entertainment", "genres": ["drama", "history"], "vote_average": 8.0, "vote_count": 9000, "popularity": 40.0, "overview": "In the antebellum United States Solomon Northup a free black man from upstate New York is abducted and sold into slavery", "imdb_id": "tt2024544", "poster_path": None},
    {"id": 857, "title": "Saving Private Ryan", "release_date": "1998-07-24", "primary_company": "DreamWorks", "genres": ["drama", "history", "war"], "vote_average": 8.2, "vote_count": 13000, "popularity": 58.0, "overview": "Following the Normandy Landings a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action", "imdb_id": "tt0120815", "poster_path": None},
    {"id": 423, "title": "The Pianist", "release_date": "2002-09-17", "primary_company": "Focus Features", "genres": ["drama", "music", "war"], "vote_average": 8.4, "vote_count": 8500, "popularity": 42.0, "overview": "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II", "imdb_id": "tt0253474", "poster_path": None},
    {"id": 11216, "title": "Cinema Paradiso", "release_date": "1988-11-17", "primary_company": "Cristaldifilm", "genres": ["drama", "romance"], "vote_average": 8.4, "vote_count": 3800, "popularity": 28.0, "overview": "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and the projection booth operator", "imdb_id": "tt0095765", "poster_path": None},
    
    # Action / Superhero
    {"id": 155, "title": "The Dark Knight", "release_date": "2008-07-18", "primary_company": "Warner Bros.", "genres": ["action", "crime", "drama"], "vote_average": 8.5, "vote_count": 30000, "popularity": 90.0, "overview": "When the menace known as the Joker wreaks havoc on Gotham Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice", "imdb_id": "tt0468569", "poster_path": None},
    {"id": 49026, "title": "The Dark Knight Rises", "release_date": "2012-07-20", "primary_company": "Warner Bros.", "genres": ["action", "crime", "drama"], "vote_average": 7.8, "vote_count": 20000, "popularity": 75.0, "overview": "Eight years after the Joker's reign of anarchy Batman is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane", "imdb_id": "tt1345836", "poster_path": None},
    {"id": 272, "title": "Batman Begins", "release_date": "2005-06-15", "primary_company": "Warner Bros.", "genres": ["action", "crime", "drama"], "vote_average": 7.7, "vote_count": 18000, "popularity": 70.0, "overview": "After training with his mentor Batman begins his fight to free crime ridden Gotham City from corruption", "imdb_id": "tt0372784", "poster_path": None},
    {"id": 98, "title": "Gladiator", "release_date": "2000-05-05", "primary_company": "DreamWorks", "genres": ["action", "drama", "adventure"], "vote_average": 8.1, "vote_count": 15000, "popularity": 62.0, "overview": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery", "imdb_id": "tt0172495", "poster_path": None},
    {"id": 24428, "title": "The Avengers", "release_date": "2012-05-04", "primary_company": "Marvel Studios", "genres": ["sciencefiction", "action", "adventure"], "vote_average": 7.7, "vote_count": 28000, "popularity": 92.0, "overview": "When an unexpected enemy emerges and threatens global safety and security Nick Fury director of the international peacekeeping agency assembles a team", "imdb_id": "tt0848228", "poster_path": None},
    {"id": 299536, "title": "Avengers: Infinity War", "release_date": "2018-04-27", "primary_company": "Marvel Studios", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 8.3, "vote_count": 25000, "popularity": 88.0, "overview": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos", "imdb_id": "tt4154756", "poster_path": None},
    {"id": 299534, "title": "Avengers: Endgame", "release_date": "2019-04-26", "primary_company": "Marvel Studios", "genres": ["adventure", "sciencefiction", "action"], "vote_average": 8.3, "vote_count": 22000, "popularity": 85.0, "overview": "After the devastating events of Infinity War the universe is in ruins and with the help of remaining allies the Avengers assemble once more to reverse Thanos actions", "imdb_id": "tt4154796", "poster_path": None},
    {"id": 1726, "title": "Iron Man", "release_date": "2008-05-02", "primary_company": "Marvel Studios", "genres": ["action", "sciencefiction", "adventure"], "vote_average": 7.6, "vote_count": 23000, "popularity": 82.0, "overview": "After being held captive in a cave billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil", "imdb_id": "tt0371746", "poster_path": None},
    {"id": 10138, "title": "Iron Man 2", "release_date": "2010-05-07", "primary_company": "Marvel Studios", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 6.8, "vote_count": 18000, "popularity": 65.0, "overview": "With the world now aware of his identity as Iron Man Tony Stark must contend with both his declining health and a vindictive rival", "imdb_id": "tt1228705", "poster_path": None},
    {"id": 68721, "title": "Iron Man 3", "release_date": "2013-05-03", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 6.9, "vote_count": 19000, "popularity": 68.0, "overview": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin he starts an odyssey of rebuilding and retribution", "imdb_id": "tt1300854", "poster_path": None},
    {"id": 1771, "title": "Captain America: The First Avenger", "release_date": "2011-07-22", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 6.9, "vote_count": 17000, "popularity": 63.0, "overview": "Steve Rogers a rejected military soldier transforms into Captain America after taking a dose of a super soldier serum", "imdb_id": "tt0458339", "poster_path": None},
    {"id": 100402, "title": "Captain America: The Winter Soldier", "release_date": "2014-04-04", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 7.7, "vote_count": 18000, "popularity": 72.0, "overview": "Steve Rogers struggles to embrace his role in the modern world and battles a new threat from old history the Soviet agent known as the Winter Soldier", "imdb_id": "tt1843866", "poster_path": None},
    {"id": 271110, "title": "Captain America: Civil War", "release_date": "2016-05-06", "primary_company": "Marvel Studios", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 7.4, "vote_count": 20000, "popularity": 75.0, "overview": "Political involvement in the Avengers affairs causes a rift between Captain America and Iron Man", "imdb_id": "tt3498820", "poster_path": None},
    {"id": 76338, "title": "Thor: The Dark World", "release_date": "2013-11-08", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "fantasy"], "vote_average": 6.5, "vote_count": 15000, "popularity": 58.0, "overview": "Thor fights to restore order across the cosmos when an ancient race led by the Dark Elf Malekith returns to plunge the universe back into darkness", "imdb_id": "tt1981115", "poster_path": None},
    {"id": 284053, "title": "Thor: Ragnarok", "release_date": "2017-11-03", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "comedy"], "vote_average": 7.6, "vote_count": 19000, "popularity": 78.0, "overview": "Thor is imprisoned on the planet Sakaar and must race against time to return to Asgard and stop Ragnarok the destruction of his world", "imdb_id": "tt3501632", "poster_path": None},
    {"id": 118340, "title": "Guardians of the Galaxy", "release_date": "2014-08-01", "primary_company": "Marvel Studios", "genres": ["action", "sciencefiction", "adventure"], "vote_average": 7.9, "vote_count": 25000, "popularity": 84.0, "overview": "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe", "imdb_id": "tt2015381", "poster_path": None},
    {"id": 283995, "title": "Guardians of the Galaxy Vol. 2", "release_date": "2017-05-05", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "comedy", "sciencefiction"], "vote_average": 7.6, "vote_count": 17000, "popularity": 72.0, "overview": "The Guardians struggle to keep together as a team while dealing with their personal family issues", "imdb_id": "tt3896198", "poster_path": None},
    {"id": 284054, "title": "Black Panther", "release_date": "2018-02-16", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 7.4, "vote_count": 21000, "popularity": 80.0, "overview": "King T'Challa returns home to Wakanda but finds his sovereignty challenged by a long time adversary in a conflict with global consequences", "imdb_id": "tt1825683", "poster_path": None},
    {"id": 315635, "title": "Spider-Man: Homecoming", "release_date": "2017-07-07", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 7.4, "vote_count": 19000, "popularity": 78.0, "overview": "Peter Parker balances his life as an ordinary high school student with his superhero alter ego Spider Man", "imdb_id": "tt2250912", "poster_path": None},
    {"id": 429617, "title": "Spider-Man: Far From Home", "release_date": "2019-07-02", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 7.5, "vote_count": 15000, "popularity": 73.0, "overview": "Peter Parker's relaxing European vacation takes an unexpected turn when Nick Fury recruits him to face a new threat", "imdb_id": "tt6320628", "poster_path": None},
    {"id": 634649, "title": "Spider-Man: No Way Home", "release_date": "2021-12-17", "primary_company": "Marvel Studios", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 8.0, "vote_count": 17000, "popularity": 90.0, "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high stakes of being a superhero", "imdb_id": "tt10872600", "poster_path": None},
    {"id": 324857, "title": "Spider-Man: Into the Spider-Verse", "release_date": "2018-12-14", "primary_company": "Sony Pictures Animation", "genres": ["animation", "action", "adventure", "sciencefiction"], "vote_average": 8.4, "vote_count": 12000, "popularity": 70.0, "overview": "Teen Miles Morales becomes the Spider Man of his reality and must join forces with counterparts from other dimensions", "imdb_id": "tt4633694", "poster_path": None},
    {"id": 533535, "title": "Deadpool & Wolverine", "release_date": "2024-07-26", "primary_company": "Marvel Studios", "genres": ["action", "comedy", "sciencefiction"], "vote_average": 7.7, "vote_count": 5000, "popularity": 95.0, "overview": "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority but instead recruits a variant of Wolverine", "imdb_id": "tt6263850", "poster_path": None},
    
    # Sci-Fi
    {"id": 27205, "title": "Inception", "release_date": "2010-07-16", "primary_company": "Warner Bros.", "genres": ["action", "sciencefiction", "adventure"], "vote_average": 8.4, "vote_count": 33000, "popularity": 85.0, "overview": "A thief who steals corporate secrets through dream sharing technology is given the inverse task of planting an idea into the mind of a CEO", "imdb_id": "tt1375666", "poster_path": None},
    {"id": 157336, "title": "Interstellar", "release_date": "2014-11-07", "primary_company": "Paramount Pictures", "genres": ["adventure", "drama", "sciencefiction"], "vote_average": 8.4, "vote_count": 31000, "popularity": 88.0, "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival on a new habitable planet", "imdb_id": "tt0816692", "poster_path": None},
    {"id": 603, "title": "The Matrix", "release_date": "1999-03-31", "primary_company": "Warner Bros.", "genres": ["action", "sciencefiction"], "vote_average": 8.2, "vote_count": 23000, "popularity": 78.0, "overview": "A computer hacker learns about the true nature of his reality and his role in the war against its controllers", "imdb_id": "tt0133093", "poster_path": None},
    {"id": 604, "title": "The Matrix Reloaded", "release_date": "2003-05-15", "primary_company": "Warner Bros.", "genres": ["action", "sciencefiction"], "vote_average": 6.7, "vote_count": 10000, "popularity": 55.0, "overview": "Neo and his allies race against time before the machines discover the city of Zion and destroy it and its inhabitants", "imdb_id": "tt0234215", "poster_path": None},
    {"id": 605, "title": "The Matrix Revolutions", "release_date": "2003-11-05", "primary_company": "Warner Bros.", "genres": ["action", "sciencefiction"], "vote_average": 6.3, "vote_count": 9000, "popularity": 50.0, "overview": "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front", "imdb_id": "tt0242653", "poster_path": None},
    {"id": 11, "title": "Star Wars", "release_date": "1977-05-25", "primary_company": "Lucasfilm", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 8.2, "vote_count": 18000, "popularity": 70.0, "overview": "Luke Skywalker joins forces with a Jedi Knight a cocky pilot a Wookiee and two droids to save the galaxy from the Empire", "imdb_id": "tt0076759", "poster_path": None},
    {"id": 1891, "title": "The Empire Strikes Back", "release_date": "1980-05-21", "primary_company": "Lucasfilm", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 8.4, "vote_count": 14000, "popularity": 65.0, "overview": "After the Rebels are overpowered by the Empire Luke Skywalker begins Jedi training with Yoda while his friends are pursued", "imdb_id": "tt0080684", "poster_path": None},
    {"id": 1892, "title": "Return of the Jedi", "release_date": "1983-05-25", "primary_company": "Lucasfilm", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 7.9, "vote_count": 13000, "popularity": 60.0, "overview": "After a rescue of Han Solo from Jabba the Hutt the Rebels attempt to destroy the second Death Star", "imdb_id": "tt0086190", "poster_path": None},
    {"id": 140607, "title": "Star Wars: The Force Awakens", "release_date": "2015-12-18", "primary_company": "Lucasfilm", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 7.3, "vote_count": 17000, "popularity": 75.0, "overview": "Thirty years after defeating the Empire a new threat arises to threaten the galaxy and a stormtrooper defector a scavenger and a droid find themselves in the center", "imdb_id": "tt2488496", "poster_path": None},
    {"id": 181808, "title": "Star Wars: The Last Jedi", "release_date": "2017-12-15", "primary_company": "Lucasfilm", "genres": ["adventure", "action", "sciencefiction"], "vote_average": 6.8, "vote_count": 14000, "popularity": 68.0, "overview": "Rey develops her newly discovered abilities with the guidance of Luke Skywalker who is unsettled by the strength of her powers", "imdb_id": "tt2527336", "poster_path": None},
    {"id": 348, "title": "Alien", "release_date": "1979-05-25", "primary_company": "20th Century Fox", "genres": ["horror", "sciencefiction"], "vote_average": 8.1, "vote_count": 12000, "popularity": 55.0, "overview": "During its return to the earth commercial spaceship Nostromo intercepts a distress signal from a distant planet that leads to a deadly encounter", "imdb_id": "tt0078748", "poster_path": None},
    {"id": 679, "title": "Aliens", "release_date": "1986-07-18", "primary_company": "20th Century Fox", "genres": ["action", "sciencefiction", "thriller"], "vote_average": 8.0, "vote_count": 10000, "popularity": 52.0, "overview": "Ellen Ripley is rescued by a deep salvage team after being in hypersleep for 57 years a the aliens have taken over the planet", "imdb_id": "tt0090605", "poster_path": None},
    {"id": 329, "title": "Jurassic Park", "release_date": "1993-06-11", "primary_company": "Universal Pictures", "genres": ["adventure", "sciencefiction", "thriller"], "vote_average": 7.9, "vote_count": 14000, "popularity": 60.0, "overview": "A pragmatic paleontologist touring an almost complete theme park is tasked with protecting kids after the park's power fails and prehistoric creatures roam free", "imdb_id": "tt0107290", "poster_path": None},
    {"id": 330, "title": "The Lost World: Jurassic Park", "release_date": "1997-05-23", "primary_company": "Universal Pictures", "genres": ["adventure", "sciencefiction", "action"], "vote_average": 6.5, "vote_count": 8000, "popularity": 45.0, "overview": "A research team is sent to an island to study dinosaurs living there but InGen has its own plans for the inhabitants", "imdb_id": "tt0119567", "poster_path": None},
    {"id": 135397, "title": "Jurassic World", "release_date": "2015-06-12", "primary_company": "Universal Pictures", "genres": ["action", "adventure", "sciencefiction", "thriller"], "vote_average": 6.7, "vote_count": 16000, "popularity": 68.0, "overview": "Twenty two years after the original Jurassic Park failed the new park Jurassic World is open for business with a genetically modified hybrid dinosaur", "imdb_id": "tt0369610", "poster_path": None},
    {"id": 19995, "title": "Avatar", "release_date": "2009-12-18", "primary_company": "20th Century Fox", "genres": ["action", "adventure", "fantasy", "sciencefiction"], "vote_average": 7.6, "vote_count": 27000, "popularity": 90.0, "overview": "A paraplegic Marine dispatched to moon Pandora on a unique mission becomes torn between following orders and protecting the world he feels is his home", "imdb_id": "tt0499549", "poster_path": None},
    {"id": 76600, "title": "Avatar: The Way of Water", "release_date": "2022-12-16", "primary_company": "20th Century Studios", "genres": ["sciencefiction", "adventure", "action"], "vote_average": 7.6, "vote_count": 10000, "popularity": 85.0, "overview": "Jake Sully and Neytiri have formed a family and are doing everything to stay together however they must leave their home and explore the vast regions of Pandora", "imdb_id": "tt1630029", "poster_path": None},
    {"id": 78, "title": "Blade Runner", "release_date": "1982-06-25", "primary_company": "Warner Bros.", "genres": ["sciencefiction", "drama", "thriller"], "vote_average": 7.9, "vote_count": 12000, "popularity": 52.0, "overview": "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator", "imdb_id": "tt0083658", "poster_path": None},
    {"id": 335984, "title": "Blade Runner 2049", "release_date": "2017-10-06", "primary_company": "Warner Bros.", "genres": ["sciencefiction", "drama"], "vote_average": 7.5, "vote_count": 11000, "popularity": 56.0, "overview": "Young Blade Runner K discovers a long buried secret that leads him to track down former Blade Runner Rick Deckard who has been missing for thirty years", "imdb_id": "tt1856101", "poster_path": None},
    {"id": 218, "title": "The Terminator", "release_date": "1984-10-26", "primary_company": "Orion Pictures", "genres": ["action", "thriller", "sciencefiction"], "vote_average": 7.6, "vote_count": 11000, "popularity": 55.0, "overview": "A cyborg assassin known as the Terminator is sent from 2029 to 1984 to kill Sarah Connor whose future son will lead the human resistance", "imdb_id": "tt0088247", "poster_path": None},
    {"id": 280, "title": "Terminator 2: Judgment Day", "release_date": "1991-07-03", "primary_company": "TriStar Pictures", "genres": ["action", "thriller", "sciencefiction"], "vote_average": 8.1, "vote_count": 11000, "popularity": 58.0, "overview": "A cyborg identical to the one who failed to kill Sarah Connor must now protect her young son from a more advanced lethal cyborg", "imdb_id": "tt0103064", "poster_path": None},
    {"id": 76341, "title": "Mad Max: Fury Road", "release_date": "2015-05-15", "primary_company": "Warner Bros.", "genres": ["action", "adventure", "sciencefiction"], "vote_average": 7.6, "vote_count": 20000, "popularity": 68.0, "overview": "In a post apocalyptic wasteland a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners and a lone drifter", "imdb_id": "tt1392190", "poster_path": None},
    {"id": 264660, "title": "Ex Machina", "release_date": "2015-04-24", "primary_company": "Film4 Productions", "genres": ["drama", "sciencefiction"], "vote_average": 7.6, "vote_count": 14000, "popularity": 55.0, "overview": "A young programmer is selected to participate in a groundbreaking experiment in synthetic intelligence by evaluating a breathtaking humanoid AI", "imdb_id": "tt0470752", "poster_path": None},
    {"id": 62, "title": "2001: A Space Odyssey", "release_date": "1968-04-02", "primary_company": "Metro-Goldwyn-Mayer", "genres": ["sciencefiction", "mystery", "adventure"], "vote_average": 8.1, "vote_count": 10000, "popularity": 48.0, "overview": "After discovering a mysterious artifact buried beneath the lunar surface humanity sets off on a quest to find its origins with the help of intelligent supercomputer HAL 9000", "imdb_id": "tt0062622", "poster_path": None},
    {"id": 152601, "title": "Her", "release_date": "2013-12-18", "primary_company": "Annapurna Pictures", "genres": ["romance", "sciencefiction", "drama"], "vote_average": 7.9, "vote_count": 14000, "popularity": 52.0, "overview": "In a near future a lonely writer develops an unlikely relationship with an operating system designed to meet his every need", "imdb_id": "tt1798709", "poster_path": None},
    {"id": 374720, "title": "Arrival", "release_date": "2016-11-11", "primary_company": "Paramount Pictures", "genres": ["drama", "sciencefiction", "mystery"], "vote_average": 7.6, "vote_count": 15000, "popularity": 55.0, "overview": "When twelve mysterious spacecraft appear around the world linguistics professor Louise Banks is tasked with interpreting the language of the alien visitors", "imdb_id": "tt2543164", "poster_path": None},
    {"id": 438631, "title": "Dune", "release_date": "2021-10-22", "primary_company": "Legendary Entertainment", "genres": ["sciencefiction", "adventure"], "vote_average": 7.8, "vote_count": 10000, "popularity": 78.0, "overview": "Paul Atreides a brilliant and gifted young man born into a great destiny beyond his understanding must travel to the most dangerous planet in the universe", "imdb_id": "tt1160419", "poster_path": None},
    {"id": 693134, "title": "Dune: Part Two", "release_date": "2024-03-01", "primary_company": "Legendary Entertainment", "genres": ["sciencefiction", "adventure"], "vote_average": 8.2, "vote_count": 5000, "popularity": 92.0, "overview": "Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family", "imdb_id": "tt15239678", "poster_path": None},
    {"id": 346364, "title": "It", "release_date": "2017-09-08", "primary_company": "New Line Cinema", "genres": ["horror", "fantasy"], "vote_average": 7.2, "vote_count": 17000, "popularity": 65.0, "overview": "In the summer of 1989 a group of bullied kids band together to destroy a shape shifting monster which disguises itself as a clown and preys on the children", "imdb_id": "tt1396484", "poster_path": None},
    {"id": 438631, "title": "Tenet", "release_date": "2020-08-26", "primary_company": "Warner Bros.", "genres": ["action", "thriller", "sciencefiction"], "vote_average": 7.2, "vote_count": 9000, "popularity": 60.0, "overview": "Armed with only one word Tenet and fighting for the survival of the entire world a protagonist journeys through a twilight world of international espionage", "imdb_id": "tt6723592", "poster_path": None},
    {"id": 438632, "title": "The Martian", "release_date": "2015-10-02", "primary_company": "20th Century Fox", "genres": ["drama", "adventure", "sciencefiction"], "vote_average": 8.0, "vote_count": 21000, "popularity": 72.0, "overview": "An astronaut becomes stranded on Mars and must devise a way to survive and signal to Earth that he is alive using limited supplies", "imdb_id": "tt3659388", "poster_path": None},
    {"id": 438633, "title": "Gravity", "release_date": "2013-10-04", "primary_company": "Warner Bros.", "genres": ["sciencefiction", "thriller", "drama"], "vote_average": 7.2, "vote_count": 14000, "popularity": 55.0, "overview": "Two astronauts work together to survive after an accident leaves them stranded in space with dwindling resources", "imdb_id": "tt1454468", "poster_path": None},
    {"id": 438634, "title": "Edge of Tomorrow", "release_date": "2014-06-06", "primary_company": "Warner Bros.", "genres": ["action", "sciencefiction"], "vote_average": 7.6, "vote_count": 13000, "popularity": 60.0, "overview": "An officer finds himself caught in a time loop in a war with aliens and his skills increase as he faces the same scenario repeatedly", "imdb_id": "tt1631867", "poster_path": None},
    {"id": 438635, "title": "District 9", "release_date": "2009-08-14", "primary_company": "TriStar Pictures", "genres": ["sciencefiction", "action", "thriller"], "vote_average": 7.4, "vote_count": 10000, "popularity": 48.0, "overview": "Aliens land in South Africa and are confined to an pointment camp and an operative tasked with relocating them contracts a mysterious virus that begins changing his identity", "imdb_id": "tt1136608", "poster_path": None},
    
    # Crime / Thriller
    {"id": 680, "title": "Pulp Fiction", "release_date": "1994-10-14", "primary_company": "Miramax", "genres": ["crime", "drama", "thriller"], "vote_average": 8.5, "vote_count": 25000, "popularity": 70.0, "overview": "The lives of two mob hitmen a boxer a gangster and his wife and a pair of diner bandits intertwine in four tales of violence and redemption", "imdb_id": "tt0110912", "poster_path": None},
    {"id": 274, "title": "The Silence of the Lambs", "release_date": "1991-02-14", "primary_company": "Orion Pictures", "genres": ["crime", "drama", "thriller"], "vote_average": 8.3, "vote_count": 14000, "popularity": 56.0, "overview": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer a madman who skins his victims", "imdb_id": "tt0102926", "poster_path": None},
    {"id": 807, "title": "Se7en", "release_date": "1995-09-22", "primary_company": "New Line Cinema", "genres": ["crime", "mystery", "thriller"], "vote_average": 8.3, "vote_count": 15000, "popularity": 59.0, "overview": "Two detectives a rookie and a veteran hunt a serial killer who uses the seven deadly sins as his motifs", "imdb_id": "tt0114369", "poster_path": None},
    {"id": 1422, "title": "The Departed", "release_date": "2006-10-06", "primary_company": "Warner Bros.", "genres": ["crime", "drama", "thriller"], "vote_average": 8.1, "vote_count": 13000, "popularity": 57.0, "overview": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston", "imdb_id": "tt0407887", "poster_path": None},
    {"id": 745, "title": "The Usual Suspects", "release_date": "1995-08-16", "primary_company": "Gramercy Pictures", "genres": ["crime", "thriller", "drama"], "vote_average": 8.2, "vote_count": 10000, "popularity": 48.0, "overview": "A sole survivor tells of the twistedly convoluted story of events leading up to a horrific gun battle on a boat", "imdb_id": "tt0114814", "poster_path": None},
    {"id": 500, "title": "Reservoir Dogs", "release_date": "1992-09-02", "primary_company": "Miramax", "genres": ["crime", "thriller"], "vote_average": 8.1, "vote_count": 12000, "popularity": 50.0, "overview": "When a simple jewelry heist goes horribly wrong the surviving criminals begin to suspect that one of them is a police informant", "imdb_id": "tt0105236", "poster_path": None},
    {"id": 773, "title": "Little Miss Sunshine", "release_date": "2006-07-26", "primary_company": "Fox Searchlight Pictures", "genres": ["comedy", "drama"], "vote_average": 7.7, "vote_count": 8000, "popularity": 42.0, "overview": "A family determined to get their young daughter into the finals of a beauty pageant take a cross country trip in their VW bus", "imdb_id": "tt0427944", "poster_path": None},
    {"id": 475557, "title": "Joker", "release_date": "2019-10-04", "primary_company": "Warner Bros.", "genres": ["crime", "thriller", "drama"], "vote_average": 8.2, "vote_count": 21000, "popularity": 75.0, "overview": "In Gotham City mentally troubled comedian Arthur Fleck is disregarded and mistreated by society he then embarks on a downward spiral of revolution and bloody crime", "imdb_id": "tt7286456", "poster_path": None},
    {"id": 489, "title": "Good Will Hunting", "release_date": "1997-12-05", "primary_company": "Miramax", "genres": ["drama", "romance"], "vote_average": 8.2, "vote_count": 10000, "popularity": 48.0, "overview": "Will Hunting a janitor at MIT has a gift for mathematics but needs help from a psychologist to find direction in his life", "imdb_id": "tt0119217", "poster_path": None},
    {"id": 568, "title": "Apollo 13", "release_date": "1995-06-30", "primary_company": "Universal Pictures", "genres": ["drama", "adventure", "history"], "vote_average": 7.6, "vote_count": 8000, "popularity": 42.0, "overview": "NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage", "imdb_id": "tt0112384", "poster_path": None},
    {"id": 438636, "title": "Zodiac", "release_date": "2007-03-02", "primary_company": "Paramount Pictures", "genres": ["crime", "drama", "mystery", "thriller"], "vote_average": 7.7, "vote_count": 8500, "popularity": 45.0, "overview": "A San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer an unidentified serial killer", "imdb_id": "tt0443706", "poster_path": None},
    {"id": 438637, "title": "Gone Girl", "release_date": "2014-10-03", "primary_company": "20th Century Fox", "genres": ["mystery", "thriller", "drama"], "vote_average": 7.9, "vote_count": 18000, "popularity": 62.0, "overview": "With his wife's disappearance having become the focus of an intense media circus a man sees the spotlight turned on him when it is suspected that he may not be innocent", "imdb_id": "tt2267998", "poster_path": None},
    {"id": 438638, "title": "Shutter Island", "release_date": "2010-02-19", "primary_company": "Paramount Pictures", "genres": ["drama", "thriller", "mystery"], "vote_average": 8.1, "vote_count": 20000, "popularity": 65.0, "overview": "U.S. Marshal Teddy Daniels is sent to investigate the disappearance of a murderess who escaped from a hospital for the criminally insane", "imdb_id": "tt1130884", "poster_path": None},
    {"id": 438639, "title": "Prisoners", "release_date": "2013-09-20", "primary_company": "Warner Bros.", "genres": ["thriller", "drama", "crime"], "vote_average": 8.1, "vote_count": 12000, "popularity": 52.0, "overview": "When the daughters of two families are abducted a father takes matters into his own hands while the police pursue multiple leads", "imdb_id": "tt1392214", "poster_path": None},
    {"id": 438640, "title": "Sicario", "release_date": "2015-09-18", "primary_company": "Lionsgate", "genres": ["action", "crime", "thriller"], "vote_average": 7.6, "vote_count": 10000, "popularity": 50.0, "overview": "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the US and Mexico", "imdb_id": "tt3397884", "poster_path": None},
    {"id": 438641, "title": "No Country for Old Men", "release_date": "2007-11-09", "primary_company": "Paramount Vantage", "genres": ["crime", "drama", "thriller"], "vote_average": 7.9, "vote_count": 12000, "popularity": 52.0, "overview": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande", "imdb_id": "tt0477348", "poster_path": None},
    {"id": 438642, "title": "Heat", "release_date": "1995-12-15", "primary_company": "Warner Bros.", "genres": ["action", "crime", "drama"], "vote_average": 8.0, "vote_count": 8000, "popularity": 48.0, "overview": "A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist", "imdb_id": "tt0113277", "poster_path": None},
    {"id": 438643, "title": "The Town", "release_date": "2010-09-17", "primary_company": "Warner Bros.", "genres": ["crime", "drama", "thriller"], "vote_average": 7.3, "vote_count": 6000, "popularity": 42.0, "overview": "A proficient bank robber plans his next heist but begins to question his future after beginning to develop a relationship with a woman he briefly took hostage", "imdb_id": "tt0840361", "poster_path": None},
    
    # Comedy
    {"id": 120, "title": "The Lord of the Rings: The Fellowship of the Ring", "release_date": "2001-12-19", "primary_company": "New Line Cinema", "genres": ["adventure", "fantasy", "action"], "vote_average": 8.4, "vote_count": 22000, "popularity": 76.0, "overview": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the One Ring and the Dark Lord Sauron", "imdb_id": "tt0120737", "poster_path": None},
    {"id": 121, "title": "The Lord of the Rings: The Two Towers", "release_date": "2002-12-18", "primary_company": "New Line Cinema", "genres": ["adventure", "fantasy", "action"], "vote_average": 8.4, "vote_count": 19000, "popularity": 74.0, "overview": "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum the scattered fellowship work to stop Saruman's forces", "imdb_id": "tt0167261", "poster_path": None},
    {"id": 122, "title": "The Lord of the Rings: The Return of the King", "release_date": "2003-12-17", "primary_company": "New Line Cinema", "genres": ["adventure", "fantasy", "action"], "vote_average": 8.5, "vote_count": 21000, "popularity": 77.0, "overview": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom", "imdb_id": "tt0167260", "poster_path": None},
    {"id": 438644, "title": "The Hobbit: An Unexpected Journey", "release_date": "2012-12-14", "primary_company": "New Line Cinema", "genres": ["adventure", "fantasy", "action"], "vote_average": 7.3, "vote_count": 16000, "popularity": 62.0, "overview": "A reluctant Hobbit Bilbo Baggins sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home", "imdb_id": "tt0903624", "poster_path": None},
    {"id": 438645, "title": "Superbad", "release_date": "2007-08-17", "primary_company": "Columbia Pictures", "genres": ["comedy"], "vote_average": 7.2, "vote_count": 9000, "popularity": 45.0, "overview": "Two co dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze fueled party goes awry", "imdb_id": "tt0829482", "poster_path": None},
    {"id": 438646, "title": "The Hangover", "release_date": "2009-06-05", "primary_company": "Warner Bros.", "genres": ["comedy"], "vote_average": 7.4, "vote_count": 13000, "popularity": 55.0, "overview": "Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the bachelor missing", "imdb_id": "tt1119646", "poster_path": None},
    {"id": 438647, "title": "Step Brothers", "release_date": "2008-07-25", "primary_company": "Columbia Pictures", "genres": ["comedy"], "vote_average": 6.7, "vote_count": 5000, "popularity": 40.0, "overview": "Two aimless middle aged losers still living at home are forced against their will to become roommates when their parents marry", "imdb_id": "tt0838283", "poster_path": None},
    {"id": 438648, "title": "Bridesmaids", "release_date": "2011-05-13", "primary_company": "Universal Pictures", "genres": ["comedy", "romance"], "vote_average": 6.8, "vote_count": 7000, "popularity": 42.0, "overview": "Annie's life is a mess but when she finds out her lifetime best friend is engaged she simply must serve as maid of honor", "imdb_id": "tt1478338", "poster_path": None},
    {"id": 438649, "title": "Borat", "release_date": "2006-11-03", "primary_company": "20th Century Fox", "genres": ["comedy"], "vote_average": 6.8, "vote_count": 7500, "popularity": 45.0, "overview": "Kazakh journalist Borat Sagdiyev travels to the United States to make a documentary which quickly turns into a quest", "imdb_id": "tt0443453", "poster_path": None},
    
    # Animated
    {"id": 862, "title": "Toy Story", "release_date": "1995-11-22", "primary_company": "Pixar", "genres": ["animation", "comedy", "family"], "vote_average": 8.0, "vote_count": 15000, "popularity": 63.0, "overview": "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room", "imdb_id": "tt0114709", "poster_path": None},
    {"id": 863, "title": "Toy Story 2", "release_date": "1999-11-24", "primary_company": "Pixar", "genres": ["animation", "comedy", "family"], "vote_average": 7.6, "vote_count": 11000, "popularity": 55.0, "overview": "When Woody is stolen by a toy collector Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy", "imdb_id": "tt0120363", "poster_path": None},
    {"id": 10193, "title": "Toy Story 3", "release_date": "2010-06-18", "primary_company": "Pixar", "genres": ["animation", "comedy", "family"], "vote_average": 7.8, "vote_count": 13000, "popularity": 58.0, "overview": "The toys are mistakenly delivered to a day care center instead of the attic right before Andy leaves for college", "imdb_id": "tt0435761", "poster_path": None},
    {"id": 12, "title": "Finding Nemo", "release_date": "2003-05-30", "primary_company": "Pixar", "genres": ["animation", "family", "comedy"], "vote_average": 8.0, "vote_count": 17000, "popularity": 65.0, "overview": "After his son is captured in the Great Barrier Reef and taken to Sydney a timid clownfish sets out on a journey to bring him home", "imdb_id": "tt0266543", "poster_path": None},
    {"id": 14160, "title": "Up", "release_date": "2009-05-29", "primary_company": "Pixar", "genres": ["animation", "comedy", "family", "adventure"], "vote_average": 8.0, "vote_count": 18000, "popularity": 64.0, "overview": "By tying thousands of balloons to his home 78 year old Carl Fredricksen sets out to fulfill his lifelong dream to see the wilds of South America", "imdb_id": "tt1049413", "poster_path": None},
    {"id": 10681, "title": "WALL-E", "release_date": "2008-06-27", "primary_company": "Pixar", "genres": ["animation", "family", "sciencefiction"], "vote_average": 8.1, "vote_count": 16000, "popularity": 62.0, "overview": "In the distant future a small waste collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind", "imdb_id": "tt0910970", "poster_path": None},
    {"id": 354912, "title": "Coco", "release_date": "2017-11-22", "primary_company": "Pixar", "genres": ["animation", "family", "fantasy", "music"], "vote_average": 8.2, "vote_count": 17000, "popularity": 64.0, "overview": "Aspiring musician Miguel enters the stunning and colorful Land of the Dead to unlock the real story behind his family history", "imdb_id": "tt2380307", "poster_path": None},
    {"id": 585, "title": "Monsters, Inc.", "release_date": "2001-11-02", "primary_company": "Pixar", "genres": ["animation", "comedy", "family"], "vote_average": 7.8, "vote_count": 15000, "popularity": 58.0, "overview": "In order to power the city monsters have to scare children so that they scream but a young girl wanders into the factory and changes everything", "imdb_id": "tt0198781", "poster_path": None},
    {"id": 150540, "title": "Inside Out", "release_date": "2015-06-19", "primary_company": "Pixar", "genres": ["animation", "family", "comedy", "drama"], "vote_average": 7.9, "vote_count": 18000, "popularity": 65.0, "overview": "After young Riley is uprooted from her Midwest life and moved to San Francisco her emotions Joy Sadness Anger Fear and Disgust conflict on how best to navigate the new city", "imdb_id": "tt2096673", "poster_path": None},
    {"id": 1124, "title": "The Incredibles", "release_date": "2004-11-05", "primary_company": "Pixar", "genres": ["animation", "action", "adventure", "family"], "vote_average": 7.7, "vote_count": 14000, "popularity": 58.0, "overview": "Bob Parr and his superhero family are forced to hide their powers and live a quiet suburban life but when a new villain emerges Bob gets back into action", "imdb_id": "tt0317705", "poster_path": None},
    {"id": 301528, "title": "Ratatouille", "release_date": "2007-06-29", "primary_company": "Pixar", "genres": ["animation", "comedy", "family", "fantasy"], "vote_average": 7.8, "vote_count": 14000, "popularity": 56.0, "overview": "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant in Paris", "imdb_id": "tt0382932", "poster_path": None},
    {"id": 129, "title": "Spirited Away", "release_date": "2001-07-20", "primary_company": "Studio Ghibli", "genres": ["animation", "family", "fantasy"], "vote_average": 8.5, "vote_count": 14000, "popularity": 60.0, "overview": "During her family's move to the suburbs a sullen 10 year old girl wanders into a world ruled by gods witches and spirits", "imdb_id": "tt0245429", "poster_path": None},
    {"id": 128, "title": "Princess Mononoke", "release_date": "1997-07-12", "primary_company": "Studio Ghibli", "genres": ["animation", "adventure", "fantasy"], "vote_average": 8.3, "vote_count": 7000, "popularity": 42.0, "overview": "On a journey to find the cure for a Tatarigami's curse Prince Ashitaka finds himself in the middle of a war between the forest gods and Tatara a mining colony", "imdb_id": "tt0119698", "poster_path": None},
    {"id": 438650, "title": "My Neighbor Totoro", "release_date": "1988-04-16", "primary_company": "Studio Ghibli", "genres": ["animation", "family", "fantasy"], "vote_average": 8.1, "vote_count": 7500, "popularity": 42.0, "overview": "Two young girls move to the country to be near their ailing mother and befriend magical forest creatures called Totoros", "imdb_id": "tt0096283", "poster_path": None},
    {"id": 438651, "title": "Howl's Moving Castle", "release_date": "2004-11-20", "primary_company": "Studio Ghibli", "genres": ["animation", "fantasy", "adventure"], "vote_average": 8.3, "vote_count": 8500, "popularity": 46.0, "overview": "When Sophie an unassuming girl is cursed with an old body by a spiteful witch her only chance of breaking the spell lies with a self indulgent wizard Howl", "imdb_id": "tt0347149", "poster_path": None},
    {"id": 508947, "title": "Turning Red", "release_date": "2022-03-11", "primary_company": "Pixar", "genres": ["animation", "family", "comedy", "fantasy"], "vote_average": 7.4, "vote_count": 7000, "popularity": 55.0, "overview": "Thirteen year old Mei is experiencing the awkwardness of being a teenager with a twist she turns into a giant red panda whenever she gets too excited", "imdb_id": "tt8097030", "poster_path": None},
    {"id": 508442, "title": "Soul", "release_date": "2020-12-25", "primary_company": "Pixar", "genres": ["animation", "comedy", "drama", "music", "fantasy"], "vote_average": 8.0, "vote_count": 10000, "popularity": 58.0, "overview": "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning about herself", "imdb_id": "tt2948372", "poster_path": None},
    {"id": 438652, "title": "Frozen", "release_date": "2013-11-27", "primary_company": "Walt Disney Pictures", "genres": ["animation", "adventure", "family", "comedy"], "vote_average": 7.3, "vote_count": 16000, "popularity": 66.0, "overview": "Young princess Anna sets off on an epic journey alongside iceman Kristoff and his reindeer to find her estranged sister Elsa and save the kingdom", "imdb_id": "tt2294629", "poster_path": None},
    {"id": 420817, "title": "Aladdin", "release_date": "1992-11-25", "primary_company": "Walt Disney Pictures", "genres": ["animation", "family", "fantasy", "romance", "comedy"], "vote_average": 7.6, "vote_count": 11000, "popularity": 55.0, "overview": "A kindhearted street urchin and a power hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true", "imdb_id": "tt0103639", "poster_path": None},
    {"id": 8587, "title": "The Lion King", "release_date": "1994-06-24", "primary_company": "Walt Disney Pictures", "genres": ["animation", "family", "drama"], "vote_average": 8.3, "vote_count": 16000, "popularity": 68.0, "overview": "A young lion prince is cast out of his pride by his cruel uncle who claims he killed his father but returns as an adult to reclaim his rightful throne", "imdb_id": "tt0110357", "poster_path": None},
    {"id": 438653, "title": "Moana", "release_date": "2016-11-23", "primary_company": "Walt Disney Pictures", "genres": ["animation", "adventure", "comedy", "family"], "vote_average": 7.6, "vote_count": 12000, "popularity": 58.0, "overview": "In ancient Polynesia when a terrible curse incurred by the demigod Maui reaches Moana's island she answers the ocean's call to seek out the demigod to set things right", "imdb_id": "tt3521164", "poster_path": None},
    {"id": 438654, "title": "Zootopia", "release_date": "2016-03-04", "primary_company": "Walt Disney Pictures", "genres": ["animation", "adventure", "family", "comedy"], "vote_average": 7.7, "vote_count": 15000, "popularity": 62.0, "overview": "In a city of anthropomorphic animals rookie bunny cop Judy Hopps is forced to work with a cynical con artist fox Nick Wilde to uncover a conspiracy", "imdb_id": "tt2948356", "poster_path": None},
    {"id": 438655, "title": "Big Hero 6", "release_date": "2014-11-07", "primary_company": "Walt Disney Pictures", "genres": ["animation", "adventure", "family", "comedy"], "vote_average": 7.8, "vote_count": 13000, "popularity": 58.0, "overview": "A special bond develops between plus sized inflatable robot Baymax and prodigy Hiro Hamada who team up with a group of friends to form a band of high tech heroes", "imdb_id": "tt2245084", "poster_path": None},
    {"id": 438656, "title": "Tangled", "release_date": "2010-11-24", "primary_company": "Walt Disney Pictures", "genres": ["animation", "family", "comedy"], "vote_average": 7.6, "vote_count": 11000, "popularity": 55.0, "overview": "The magically long haired Rapunzel has spent her life in a tower but when she falls in love with a daring bandit she leaves to find the floating lights", "imdb_id": "tt0398286", "poster_path": None},
    {"id": 438657, "title": "Wreck-It Ralph", "release_date": "2012-11-02", "primary_company": "Walt Disney Pictures", "genres": ["animation", "family", "comedy"], "vote_average": 7.2, "vote_count": 11000, "popularity": 52.0, "overview": "A video game villain wants to be a hero and sets out to fulfill his dream but his quest brings havoc to the whole arcade", "imdb_id": "tt1772341", "poster_path": None},
    {"id": 438658, "title": "Shrek", "release_date": "2001-05-18", "primary_company": "DreamWorks Animation", "genres": ["animation", "comedy", "family", "fantasy"], "vote_average": 7.7, "vote_count": 15000, "popularity": 60.0, "overview": "An ogre in order to regain his swamp strikes a deal with evil Lord Farquaad and sets out to rescue Princess Fiona to be Lord Farquaad's bride", "imdb_id": "tt0126029", "poster_path": None},
    {"id": 438659, "title": "Shrek 2", "release_date": "2004-05-19", "primary_company": "DreamWorks Animation", "genres": ["animation", "comedy", "family", "fantasy"], "vote_average": 7.3, "vote_count": 12000, "popularity": 55.0, "overview": "Shrek and Fiona travel to the Kingdom of Far Far Away where Fiona's parents are King and Queen to celebrate their marriage", "imdb_id": "tt0298148", "poster_path": None},
    {"id": 438660, "title": "How to Train Your Dragon", "release_date": "2010-03-26", "primary_company": "DreamWorks Animation", "genres": ["animation", "family", "adventure", "fantasy", "comedy"], "vote_average": 7.8, "vote_count": 13000, "popularity": 58.0, "overview": "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself and learns there may be more to the creatures than he assumed", "imdb_id": "tt0892769", "poster_path": None},
    {"id": 438661, "title": "Kung Fu Panda", "release_date": "2008-06-06", "primary_company": "DreamWorks Animation", "genres": ["animation", "action", "adventure", "comedy", "family"], "vote_average": 7.3, "vote_count": 12000, "popularity": 55.0, "overview": "When the Valley of Peace is threatened the lazy panda Po must become the Dragon Warrior and train under Master Shifu", "imdb_id": "tt0441773", "poster_path": None},

    # Mystery / Psychological / Thriller
    {"id": 745, "title": "The Sixth Sense", "release_date": "1999-08-06", "primary_company": "Hollywood Pictures", "genres": ["mystery", "thriller", "drama"], "vote_average": 7.9, "vote_count": 12000, "popularity": 52.0, "overview": "A boy who communicates with spirits seeks the help of a disheartened child psychologist", "imdb_id": "tt0167404", "poster_path": None},
    {"id": 438662, "title": "Memento", "release_date": "2000-10-11", "primary_company": "Newmarket Films", "genres": ["mystery", "thriller"], "vote_average": 8.2, "vote_count": 13000, "popularity": 55.0, "overview": "A man with short term memory loss attempts to track down his wife's murderer using notes and tattoos", "imdb_id": "tt0209144", "poster_path": None},
    {"id": 438663, "title": "The Prestige", "release_date": "2006-10-20", "primary_company": "Touchstone Pictures", "genres": ["drama", "mystery", "sciencefiction"], "vote_average": 8.2, "vote_count": 14000, "popularity": 60.0, "overview": "After a tragic accident two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything", "imdb_id": "tt0482571", "poster_path": None},
    {"id": 438664, "title": "The Truman Show", "release_date": "1998-06-05", "primary_company": "Paramount Pictures", "genres": ["comedy", "drama"], "vote_average": 8.1, "vote_count": 15000, "popularity": 58.0, "overview": "An insurance salesman discovers his whole life is actually a reality TV show and sets out to find the truth and escape", "imdb_id": "tt0120382", "poster_path": None},
    {"id": 438665, "title": "Eternal Sunshine of the Spotless Mind", "release_date": "2004-03-19", "primary_company": "Focus Features", "genres": ["sciencefiction", "drama", "romance"], "vote_average": 8.1, "vote_count": 12000, "popularity": 50.0, "overview": "When their relationship turns sour a couple undergoes a medical procedure to have each other erased from their memories", "imdb_id": "tt0338013", "poster_path": None},
    {"id": 438666, "title": "Oldboy", "release_date": "2003-11-21", "primary_company": "Show East", "genres": ["thriller", "drama", "mystery", "action"], "vote_average": 8.3, "vote_count": 7000, "popularity": 40.0, "overview": "After being kidnapped and imprisoned for fifteen years Oh Dae Su is released only to find that he must find his captor in five days", "imdb_id": "tt0364569", "poster_path": None},
    {"id": 438667, "title": "Black Swan", "release_date": "2010-12-03", "primary_company": "Fox Searchlight Pictures", "genres": ["drama", "thriller", "horror"], "vote_average": 7.8, "vote_count": 14000, "popularity": 55.0, "overview": "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's Swan Lake", "imdb_id": "tt0947798", "poster_path": None},
    
    # International hits
    {"id": 496243, "title": "Parasite", "release_date": "2019-05-30", "primary_company": "Barunson E&A", "genres": ["comedy", "thriller", "drama"], "vote_average": 8.5, "vote_count": 15000, "popularity": 70.0, "overview": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan", "imdb_id": "tt6751668", "poster_path": None},
    {"id": 438668, "title": "Amélie", "release_date": "2001-04-25", "primary_company": "Claudie Ossard Productions", "genres": ["comedy", "romance"], "vote_average": 7.9, "vote_count": 11000, "popularity": 48.0, "overview": "Amélie is an innocent and naive girl in Paris with her own sense of justice who decides to help those around her and discovers love along the way", "imdb_id": "tt0211915", "poster_path": None},
    {"id": 438669, "title": "Pan's Labyrinth", "release_date": "2006-10-11", "primary_company": "Telecinco Cinema", "genres": ["fantasy", "drama", "war"], "vote_average": 8.0, "vote_count": 11000, "popularity": 48.0, "overview": "In the Falangist Spain of 1944 a girl fascinated with fairy tales is sent along with her ailing mother to live with her new stepfather a sadistic army officer", "imdb_id": "tt0457430", "poster_path": None},
    {"id": 438670, "title": "Crouching Tiger, Hidden Dragon", "release_date": "2000-07-06", "primary_company": "Columbia Pictures", "genres": ["action", "adventure", "drama"], "vote_average": 7.5, "vote_count": 6000, "popularity": 38.0, "overview": "Two warriors in pursuit of a stolen sword and a bamboo forest showdown help reveal an ancient world of hidden emotions and forbidden love", "imdb_id": "tt0190332", "poster_path": None},
    {"id": 438671, "title": "City of God", "release_date": "2002-08-30", "primary_company": "O2 Filmes", "genres": ["crime", "drama"], "vote_average": 8.4, "vote_count": 7000, "popularity": 42.0, "overview": "In the slums of Rio de Janeiro two kids paths diverge as one struggles to become a photographer and the other a drug dealer", "imdb_id": "tt0317248", "poster_path": None},
    {"id": 438672, "title": "The Intouchables", "release_date": "2011-11-02", "primary_company": "Gaumont", "genres": ["drama", "comedy"], "vote_average": 8.3, "vote_count": 14000, "popularity": 52.0, "overview": "After becoming a quadriplegic an aristocrat hires a young man from the housing projects to be his caretaker and an unexpected friendship develops", "imdb_id": "tt1675434", "poster_path": None},
    {"id": 438673, "title": "RRR", "release_date": "2022-03-25", "primary_company": "DVV Entertainment", "genres": ["action", "drama", "history"], "vote_average": 7.8, "vote_count": 5000, "popularity": 60.0, "overview": "A fictitious story about two legendary revolutionaries and their journey away from home before they began fighting for their country in the 1920s", "imdb_id": "tt8178634", "poster_path": None},
    {"id": 438674, "title": "3 Idiots", "release_date": "2009-12-25", "primary_company": "Vinod Chopra Films", "genres": ["comedy", "drama"], "vote_average": 8.2, "vote_count": 5000, "popularity": 42.0, "overview": "Two friends are searching for their long lost companion who inspired them to think differently even as the rest tried to convince them to think alike", "imdb_id": "tt1187043", "poster_path": None},
    {"id": 438675, "title": "Dangal", "release_date": "2016-12-23", "primary_company": "Aamir Khan Productions", "genres": ["drama", "action"], "vote_average": 8.4, "vote_count": 4000, "popularity": 40.0, "overview": "Based on the true story of Mahavir Singh Phogat who taught wrestling to his daughters despite societal norms leading them to win at the Commonwealth Games", "imdb_id": "tt5074352", "poster_path": None},
    {"id": 438676, "title": "Lagaan", "release_date": "2001-06-15", "primary_company": "Aamir Khan Productions", "genres": ["drama", "adventure", "history"], "vote_average": 7.9, "vote_count": 3500, "popularity": 35.0, "overview": "The villagers of a small village in 1890s India stake their future on a cricket match against their ruthless British rulers", "imdb_id": "tt0169102", "poster_path": None},
    
    # Horror
    {"id": 438677, "title": "Get Out", "release_date": "2017-02-24", "primary_company": "Blumhouse Productions", "genres": ["horror", "mystery", "thriller"], "vote_average": 7.6, "vote_count": 15000, "popularity": 58.0, "overview": "A young African American visits his white girlfriend's parents for the weekend where his simmering uneasiness about their reception of him eventually reaches a boiling point", "imdb_id": "tt5052448", "poster_path": None},
    {"id": 438678, "title": "A Quiet Place", "release_date": "2018-04-06", "primary_company": "Paramount Pictures", "genres": ["horror", "drama", "sciencefiction"], "vote_average": 7.4, "vote_count": 12000, "popularity": 55.0, "overview": "In a post apocalyptic world a family is forced to live in silence while hiding from monsters with ultra sensitive hearing", "imdb_id": "tt6644200", "poster_path": None},
    {"id": 438679, "title": "The Conjuring", "release_date": "2013-07-19", "primary_company": "New Line Cinema", "genres": ["horror", "thriller"], "vote_average": 7.5, "vote_count": 13000, "popularity": 56.0, "overview": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse", "imdb_id": "tt1457767", "poster_path": None},
    {"id": 438680, "title": "Hereditary", "release_date": "2018-06-08", "primary_company": "A24", "genres": ["horror", "mystery", "thriller"], "vote_average": 7.3, "vote_count": 8000, "popularity": 48.0, "overview": "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother", "imdb_id": "tt7784604", "poster_path": None},
    {"id": 438681, "title": "The Shining", "release_date": "1980-05-23", "primary_company": "Warner Bros.", "genres": ["horror", "thriller"], "vote_average": 8.2, "vote_count": 15000, "popularity": 58.0, "overview": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence while his psychic son sees horrific forebodings", "imdb_id": "tt0081505", "poster_path": None},
    {"id": 438682, "title": "The Exorcist", "release_date": "1973-12-26", "primary_company": "Warner Bros.", "genres": ["horror"], "vote_average": 7.7, "vote_count": 8000, "popularity": 45.0, "overview": "When a young girl is possessed by a demon her mother seeks the help of two Catholic priests to save her", "imdb_id": "tt0070047", "poster_path": None},
    {"id": 438683, "title": "Midsommar", "release_date": "2019-07-03", "primary_company": "A24", "genres": ["horror", "drama", "mystery"], "vote_average": 7.1, "vote_count": 8500, "popularity": 50.0, "overview": "A couple travels to Sweden to visit a rural hometown's fabled mid summer festival but what begins as an idyllic retreat soon devolves into an increasingly disturbing competition", "imdb_id": "tt8772262", "poster_path": None},
    {"id": 438684, "title": "Us", "release_date": "2019-03-22", "primary_company": "Monkeypaw Productions", "genres": ["horror", "thriller", "mystery"], "vote_average": 6.9, "vote_count": 9000, "popularity": 52.0, "overview": "A family's serene beach getaway turns to chaos when their doppelgangers appear and begin to terrorize them", "imdb_id": "tt6857112", "poster_path": None},
    {"id": 438685, "title": "The Babadook", "release_date": "2014-01-17", "primary_company": "Screen Australia", "genres": ["horror", "drama"], "vote_average": 6.7, "vote_count": 5000, "popularity": 35.0, "overview": "A single mother plagued by the violent death of her husband battles with her son's fear of a monster lurking in the house but soon discovers a sinister presence all around her", "imdb_id": "tt2321549", "poster_path": None},
    
    # Romance / Drama
    {"id": 438686, "title": "Titanic", "release_date": "1997-12-19", "primary_company": "Paramount Pictures", "genres": ["drama", "romance"], "vote_average": 7.9, "vote_count": 22000, "popularity": 72.0, "overview": "A seventeen year old aristocrat falls in love with a kind but poor artist aboard the luxurious ill fated Titanic", "imdb_id": "tt0120338", "poster_path": None},
    {"id": 438687, "title": "La La Land", "release_date": "2016-12-09", "primary_company": "Summit Entertainment", "genres": ["comedy", "drama", "romance", "music"], "vote_average": 7.9, "vote_count": 14000, "popularity": 58.0, "overview": "Mia an aspiring actress and Sebastian a dedicated jazz musician are struggling to make ends meet in Los Angeles while pursuing their dreams", "imdb_id": "tt3783958", "poster_path": None},
    {"id": 438688, "title": "The Notebook", "release_date": "2004-06-25", "primary_company": "New Line Cinema", "genres": ["romance", "drama"], "vote_average": 7.9, "vote_count": 11000, "popularity": 52.0, "overview": "A poor yet passionate young man falls in love with a rich young woman giving her a sense of freedom but they are soon separated because of their social differences", "imdb_id": "tt0332280", "poster_path": None},
    {"id": 438689, "title": "Pride and Prejudice", "release_date": "2005-11-11", "primary_company": "Working Title Films", "genres": ["drama", "romance"], "vote_average": 7.9, "vote_count": 8000, "popularity": 45.0, "overview": "A sparkling adaptation of Jane Austen's novel set in Georgian England following the Bennet family and particularly Elizabeth's turbulent relationship with Mr Darcy", "imdb_id": "tt0414387", "poster_path": None},
    {"id": 438690, "title": "500 Days of Summer", "release_date": "2009-07-17", "primary_company": "Fox Searchlight Pictures", "genres": ["comedy", "drama", "romance"], "vote_average": 7.3, "vote_count": 10000, "popularity": 48.0, "overview": "An offbeat romantic comedy about a boy meets girl story and the anatomy of a breakup told from his perspective", "imdb_id": "tt1022603", "poster_path": None},
    {"id": 438691, "title": "Before Sunrise", "release_date": "1995-01-27", "primary_company": "Columbia Pictures", "genres": ["drama", "romance"], "vote_average": 8.0, "vote_count": 5500, "popularity": 35.0, "overview": "A young man and woman meet on a train in Europe and end up spending one night together in Vienna as they explore the city and fall for each other", "imdb_id": "tt0112471", "poster_path": None},
    {"id": 438692, "title": "The Grand Budapest Hotel", "release_date": "2014-03-28", "primary_company": "Fox Searchlight Pictures", "genres": ["comedy", "drama", "adventure"], "vote_average": 8.1, "vote_count": 14000, "popularity": 55.0, "overview": "A writer encounters the owner of an aging high class hotel who tells him of his early years serving as a lobby boy in the hotel's glorious years", "imdb_id": "tt2278388", "poster_path": None},
    {"id": 438693, "title": "Moonlight", "release_date": "2016-10-21", "primary_company": "A24", "genres": ["drama"], "vote_average": 7.4, "vote_count": 8000, "popularity": 42.0, "overview": "A chronicle of the childhood adolescence and burgeoning adulthood of a young black man growing up in a rough neighborhood of Miami", "imdb_id": "tt4975722", "poster_path": None},
    
    # Whiplash/ Recent Excellence
    {"id": 244786, "title": "Whiplash", "release_date": "2014-10-10", "primary_company": "Bold Films", "genres": ["drama", "music"], "vote_average": 8.3, "vote_count": 13000, "popularity": 54.0, "overview": "A promising young drummer enrolls at a cut throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing", "imdb_id": "tt2582802", "poster_path": None},
    {"id": 438694, "title": "Django Unchained", "release_date": "2012-12-25", "primary_company": "Columbia Pictures", "genres": ["drama", "western"], "vote_average": 8.1, "vote_count": 24000, "popularity": 66.0, "overview": "With the help of a German bounty hunter a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner", "imdb_id": "tt1853728", "poster_path": None},
    {"id": 438695, "title": "Inglourious Basterds", "release_date": "2009-08-21", "primary_company": "Universal Pictures", "genres": ["drama", "thriller", "war"], "vote_average": 8.2, "vote_count": 19000, "popularity": 62.0, "overview": "In Nazi occupied France during World War II a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans", "imdb_id": "tt0361748", "poster_path": None},
    {"id": 438696, "title": "Kill Bill: Volume 1", "release_date": "2003-10-10", "primary_company": "Miramax", "genres": ["action", "crime"], "vote_average": 8.0, "vote_count": 15000, "popularity": 58.0, "overview": "After awakening from a four year coma a former assassin wreaks vengeance on the team of assassins who betrayed her", "imdb_id": "tt0266697", "poster_path": None},
    {"id": 438697, "title": "Everything Everywhere All at Once", "release_date": "2022-03-25", "primary_company": "A24", "genres": ["action", "adventure", "sciencefiction", "comedy"], "vote_average": 7.8, "vote_count": 10000, "popularity": 70.0, "overview": "An aging Chinese immigrant gets swept up in an insane adventure where she alone can save the world by exploring other universes connecting with the lives she could have lived", "imdb_id": "tt6710474", "poster_path": None},
    {"id": 438698, "title": "Oppenheimer", "release_date": "2023-07-21", "primary_company": "Universal Pictures", "genres": ["drama", "history"], "vote_average": 8.1, "vote_count": 8000, "popularity": 85.0, "overview": "The story of J Robert Oppenheimer and his role in the development of the atomic bomb during World War II and the consequences that followed", "imdb_id": "tt15398776", "poster_path": None},
    {"id": 438699, "title": "The Batman", "release_date": "2022-03-04", "primary_company": "Warner Bros.", "genres": ["crime", "mystery", "thriller"], "vote_average": 7.7, "vote_count": 10000, "popularity": 78.0, "overview": "In his second year of fighting crime Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler", "imdb_id": "tt1877830", "poster_path": None},
    {"id": 438700, "title": "Top Gun: Maverick", "release_date": "2022-05-27", "primary_company": "Paramount Pictures", "genres": ["action", "drama"], "vote_average": 8.3, "vote_count": 8000, "popularity": 80.0, "overview": "After thirty years of service as a top naval aviator Pete Mitchell is back where he belongs pushing the envelope as a test pilot and training a new generation of Top Gun graduates", "imdb_id": "tt1745960", "poster_path": None},
    {"id": 438701, "title": "Barbie", "release_date": "2023-07-21", "primary_company": "Warner Bros.", "genres": ["comedy", "adventure", "fantasy"], "vote_average": 7.0, "vote_count": 7000, "popularity": 85.0, "overview": "Barbie suffers a crisis that leads her to question her world and her existence as she and Ken leave Barbieland to enter the real world", "imdb_id": "tt1517268", "poster_path": None},
    {"id": 438702, "title": "John Wick", "release_date": "2014-10-24", "primary_company": "Summit Entertainment", "genres": ["action", "thriller"], "vote_average": 7.4, "vote_count": 14000, "popularity": 60.0, "overview": "An ex hit man comes out of retirement to track down the gangsters that killed his dog and took everything from him", "imdb_id": "tt2911666", "poster_path": None},
    {"id": 438703, "title": "John Wick: Chapter 4", "release_date": "2023-03-24", "primary_company": "Summit Entertainment", "genres": ["action", "thriller", "crime"], "vote_average": 7.8, "vote_count": 6000, "popularity": 72.0, "overview": "John Wick uncovers a path to defeating the High Table and earning his freedom but must face a new enemy with powerful alliances across the globe", "imdb_id": "tt10366206", "poster_path": None},
    {"id": 438704, "title": "The Social Network", "release_date": "2010-10-01", "primary_company": "Columbia Pictures", "genres": ["drama"], "vote_average": 7.4, "vote_count": 11000, "popularity": 50.0, "overview": "On a fall night in 2003 Harvard undergrad and computer programming genius Mark Zuckerberg begins working on a new idea that will eventually become Facebook", "imdb_id": "tt1285016", "poster_path": None},
    {"id": 438705, "title": "The Wolf of Wall Street", "release_date": "2013-12-25", "primary_company": "Paramount Pictures", "genres": ["crime", "drama", "comedy"], "vote_average": 8.0, "vote_count": 22000, "popularity": 68.0, "overview": "Based on the true story of Jordan Belfort from his rise to a wealthy stockbroker living the high life to his fall involving crime corruption and the federal government", "imdb_id": "tt0993846", "poster_path": None},
    {"id": 438706, "title": "The Big Short", "release_date": "2015-12-11", "primary_company": "Plan B Entertainment", "genres": ["comedy", "drama"], "vote_average": 7.3, "vote_count": 9000, "popularity": 48.0, "overview": "In 2006 a group of investors bet against the US mortgage market based on their research that predicts the market crash of 2008", "imdb_id": "tt1596363", "poster_path": None},
    {"id": 438707, "title": "Catch Me If You Can", "release_date": "2002-12-25", "primary_company": "DreamWorks", "genres": ["drama", "crime", "comedy"], "vote_average": 8.0, "vote_count": 14000, "popularity": 55.0, "overview": "The true story of Frank Abagnale who before his 19th birthday successfully conned millions of dollars worth of checks as a Pan Am pilot doctor and legal prosecutor", "imdb_id": "tt0264464", "poster_path": None},
    {"id": 438708, "title": "The Revenant", "release_date": "2015-12-25", "primary_company": "20th Century Fox", "genres": ["western", "drama", "adventure"], "vote_average": 7.5, "vote_count": 17000, "popularity": 62.0, "overview": "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team", "imdb_id": "tt1663202", "poster_path": None},
    {"id": 438709, "title": "Birdman", "release_date": "2014-10-17", "primary_company": "Fox Searchlight Pictures", "genres": ["drama", "comedy"], "vote_average": 7.5, "vote_count": 11000, "popularity": 48.0, "overview": "A washed up actor who once played an iconic superhero battles his ego and attempts to recover his family career and himself in the days leading up to the opening of a Broadway play", "imdb_id": "tt2562232", "poster_path": None},
    {"id": 438710, "title": "Bohemian Rhapsody", "release_date": "2018-11-02", "primary_company": "20th Century Fox", "genres": ["music", "drama", "history"], "vote_average": 8.0, "vote_count": 15000, "popularity": 62.0, "overview": "A chronicle of the years leading up to Queen's legendary appearance at the Live Aid concert in 1985 focusing on singer Freddie Mercury", "imdb_id": "tt1727824", "poster_path": None},
    {"id": 438711, "title": "A Beautiful Mind", "release_date": "2001-12-21", "primary_company": "Universal Pictures", "genres": ["drama", "romance"], "vote_average": 7.9, "vote_count": 8000, "popularity": 45.0, "overview": "After John Nash a brilliant but asocial mathematician accepts secret work in cryptography his life takes a turn for the nightmarish", "imdb_id": "tt0268978", "poster_path": None},
    {"id": 438712, "title": "Slumdog Millionaire", "release_date": "2008-11-12", "primary_company": "Fox Searchlight Pictures", "genres": ["drama", "romance"], "vote_average": 8.0, "vote_count": 12000, "popularity": 50.0, "overview": "A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of Who Wants to Be A Millionaire", "imdb_id": "tt1010048", "poster_path": None},
    {"id": 438713, "title": "The Curious Case of Benjamin Button", "release_date": "2008-12-25", "primary_company": "Paramount Pictures", "genres": ["drama", "fantasy", "romance"], "vote_average": 7.5, "vote_count": 11000, "popularity": 50.0, "overview": "Born under unusual circumstances Benjamin Button springs into being as an elderly man in a New Orleans nursing home and ages in reverse", "imdb_id": "tt0421715", "poster_path": None},
    {"id": 438714, "title": "Marriage Story", "release_date": "2019-11-06", "primary_company": "Netflix", "genres": ["drama", "romance"], "vote_average": 7.7, "vote_count": 7000, "popularity": 48.0, "overview": "Noah Baumbach's incisive and compassionate look at a marriage breaking up and a family staying together", "imdb_id": "tt7653254", "poster_path": None},
    {"id": 438715, "title": "1917", "release_date": "2019-12-25", "primary_company": "DreamWorks", "genres": ["war", "drama", "action"], "vote_average": 7.9, "vote_count": 11000, "popularity": 58.0, "overview": "Two young British soldiers during World War I given an impossible mission to deliver a message deep in enemy territory that will stop 1600 men from walking into a deadly trap", "imdb_id": "tt8579674", "poster_path": None},
    {"id": 438716, "title": "Dunkirk", "release_date": "2017-07-21", "primary_company": "Warner Bros.", "genres": ["war", "drama", "action", "history"], "vote_average": 7.5, "vote_count": 13000, "popularity": 55.0, "overview": "Allied soldiers from Belgium the British Empire and France are surrounded by the German Army and evacuated during a fierce battle in World War II", "imdb_id": "tt5013056", "poster_path": None},
    {"id": 438717, "title": "Hacksaw Ridge", "release_date": "2016-11-04", "primary_company": "Summit Entertainment", "genres": ["drama", "history", "war"], "vote_average": 8.2, "vote_count": 11000, "popularity": 52.0, "overview": "The true story of Desmond Doss who in Okinawa during the bloodiest battle of WWII saved 75 men without firing or carrying a gun", "imdb_id": "tt2119532", "poster_path": None},
    {"id": 438718, "title": "Platoon", "release_date": "1986-12-19", "primary_company": "Orion Pictures", "genres": ["drama", "war"], "vote_average": 7.6, "vote_count": 5000, "popularity": 38.0, "overview": "A young recruit in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man", "imdb_id": "tt0091763", "poster_path": None},
    {"id": 438719, "title": "Full Metal Jacket", "release_date": "1987-06-26", "primary_company": "Warner Bros.", "genres": ["drama", "war"], "vote_average": 8.0, "vote_count": 7000, "popularity": 42.0, "overview": "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their boot camp training to the bloody street fighting in Hue", "imdb_id": "tt0093058", "poster_path": None},
    {"id": 438720, "title": "Apocalypse Now", "release_date": "1979-08-15", "primary_company": "United Artists", "genres": ["drama", "war"], "vote_average": 8.4, "vote_count": 8000, "popularity": 42.0, "overview": "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god", "imdb_id": "tt0078788", "poster_path": None},
]

# De-duplicate by title (use the first occurrence)
seen_titles = set()
movies = []
for m in movies_data:
    if m["title"] not in seen_titles:
        seen_titles.add(m["title"])
        movies.append(m)

print(f"Creating demo model with {len(movies)} unique movies...")

# Build DataFrame
df = pd.DataFrame(movies)

# Save metadata as parquet
df.to_parquet(OUTPUT_DIR / "movie_metadata.parquet", compression="gzip", index=True)
print(f"  ✅ movie_metadata.parquet ({len(df)} movies)")

# Build similarity matrix using genre overlap + overview word overlap + company bonus
n = len(df)
similarity = np.eye(n, dtype=np.float32)  # diagonal = 1.0

# Pre-compute genre sets and word sets for performance
genre_sets = [set(df.iloc[i]["genres"]) for i in range(n)]
word_sets = [set(str(df.iloc[i]["overview"]).lower().split()) for i in range(n)]
companies = [df.iloc[i]["primary_company"] for i in range(n)]

print("  Computing similarity matrix...")
for i in range(n):
    for j in range(i + 1, n):
        genres_i, genres_j = genre_sets[i], genre_sets[j]
        genre_sim = len(genres_i & genres_j) / max(len(genres_i | genres_j), 1)

        words_i, words_j = word_sets[i], word_sets[j]
        word_sim = len(words_i & words_j) / max(len(words_i | words_j), 1)

        company_bonus = 0.15 if companies[i] == companies[j] else 0.0

        score = 0.50 * genre_sim + 0.35 * word_sim + 0.15 * company_bonus
        similarity[i][j] = score
        similarity[j][i] = score

# Save as sparse matrix
sparse_sim = csr_matrix(similarity)
save_npz(OUTPUT_DIR / "similarity_matrix.npz", sparse_sim)
print("  ✅ similarity_matrix.npz")

# Save title-to-index mapping
title_to_idx = {row["title"]: idx for idx, row in df.iterrows()}
with open(OUTPUT_DIR / "title_to_idx.json", "w") as f:
    json.dump(title_to_idx, f, indent=2)
print("  ✅ title_to_idx.json")

# Save config
config = {
    "n_movies": len(df),
    "use_svd": False,
    "n_components": None,
    "matrix_shape": [n, n],
    "dataset": f"CinemaLens Demo ({len(df)} popular movies)"
}
with open(OUTPUT_DIR / "config.json", "w") as f:
    json.dump(config, f, indent=2)
print("  ✅ config.json")

print(f"\n🎉 Demo model generated with {len(df)} movies in '{OUTPUT_DIR}/'")
